services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "" # root tanpa password
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: db_inventory
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    db_data:
